id: AEE4A474C
title: Complete text
type: translation
source_metadata:
  languages:
  - sa
  - pgd
  - pi
  datatype: PlainText
  created_at: 2022-03-02 08:56:19.448186
  last_modified_at: 2022-03-02 08:56:19.448199
